### ISSUE TITLE
Just getting started with S3.  Making Less3 work.

### ISSUE THREAD

**Issue by thorhalbert** [jchristn/Less3#1]
I have gotten Less3 running (visual studio 2019 - windows), connect to Sql/Server 2019.
For now, I will be mounting these with the fuse-s3fs, and likely later as docker storage.

I am quite the beginner on S3, so likely missing things.

It did not seem to create me any default user or default, account, so I created my own...   Watson did create all the schemas for the tables, so not hard to figure out.

`INSERT INTO [dbo].[users]
           ([guid]
           ,[name]
           ,[email])
     VALUES
           (newid()
           ,'thor'
           ,'thorhalbert@gmail.com')
GO`

`INSERT INTO [dbo].[credential]
           ([guid]
           ,[userguid]
           ,[description]
           ,[accesskey]
           ,[secretkey]
           ,[isbase64])
     VALUES
           (newid()
           ,'E86D8681-A474-4876-A710-B4464D66CFFE'
           ,'Thor Test Account'
           ,'ABCDEFG'
           ,'ReindeerFlotilla'
           ,0)
GO`

I may have to create ACLs for this user.

I am reasonably baffled by the accesskey and the secretkey.  All of the examples I see out of them show them as a 16 digit key and a binary (probably base64 string), like they were some component of an encryption pair.

So, I need to setup buckets and such, and so downloaded S3 browser as you suggest.   

But, I get HMAC errors...

![image](https://user-images.githubusercontent.com/7507752/93006353-f875b680-f50f-11ea-9fef-c22014dbca0a.png)

![image](https://user-images.githubusercontent.com/7507752/93006361-0b888680-f510-11ea-9e59-6fd1bcdf604d.png)

So, it rather seems me like it's trying to sign things with those keys, and that my choices for keys and secrets are bogus, though your examples are default/default, seemly just strings like I used.

I have been unable to find a command like tool to generate an AWS like key/secret set (without getting them from AWS itself).   Seems like there would be one out there, or some trick to allow me to do it in openssl or similar.   I'm not unfamiliar with crypto and hmac, but don't quite know what's being used here.

I'm ultimately wanting to write my own storage classes for Less3 to abstract several filesystems that I have, but have not yet gotten to "hello world" yet.

Thanks for your efforts!

---Thor Halbert

**Comment by jchristn** [comment]
Hi @thorhalbert I'm not sure why I never received a notification for this.  Were you able to get the issue resolved?  Sorry for necro'ing something so old.  Please feel free to email me.
