### ISSUE TITLE
Less3 host / port

### ISSUE THREAD

**Issue by dialtonetech** [jchristn/Less3#2]
Hi, I have set up Less3 on sever with domain and port xxxx, S3 Browser 10.0.9 works and I can upload image to bucket.

However when using the AWS SDK with the following code, host is not found.

var s3Config = new AmazonS3Config();
s3Config.ServiceURL = "http://storage.abc.co.za:3435";
                
                using (var cli = new AmazonS3Client("default","default",s3Config))
                {                    
                    var utility = new TransferUtility(cli);
                    await utility.UploadAsync(filePic.Path, "mibbmedia");
                }
                

Any pointers would be a great help.

**Comment by jchristn** [comment]
Hi @dialtonetech I'm not sure why I didn't receive a notification about this!  Were you able to get the issue resolved?  Please feel free to email me.  So sorry for taking *forever* to get back to you, again, I didn't get a notification.
