### ISSUE TITLE
Does Less3 support resume?

### ISSUE THREAD

**Issue by mehranrezaei** [jchristn/Less3#4]
I am very happy that I found this project and also thank you so much for publishing your work.
I want to know if this implementation supports resume for uploading and downloading?

Does it support multipart uploads? [(doc)](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html)
Does it support range header for downloads? [(doc)](https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/use-byte-range-fetches.html)
Thanks.

**Comment by jchristn** [comment]
Hi @mehranrezaei I'm so sorry I'm only seeing this now.  I'm not sure why I didn't get a notification!  It should support range reads today, but not multipart/POST uploads.  Cheers
